Get rid of compilation error under arduino-1.6.5-r5
Without modification I get in Arduino arduino-1.6.5-r5 compilation error

RF24_config.h:45:51: error: __c causes a section type conflict with __c
WString.h:in expansion of macro 'PSTR'
Sensors.pde:in expansion of macro 'F'
RF24_config.h:'__c' was declared here
WString.h:in expansion of macro 'PSTR'